[Distribution]
Architecture=x86-64
Distribution=ubuntu
Release=resolute
Repositories=universe

[Build]
Incremental=true
ToolsTree=default

[Output]
Format=disk

[Content]
Bootable=false
Bootloader=none
Initrds=
Packages=
WithDocs=false
