[Distribution]
Architecture=x86-64
Distribution=ubuntu
Release=resolute
Repositories=universe

[Build]
Incremental=true
ToolsTree=default

[Content]
Bootable=true
CleanPackageMetadata=yes
WithDocs=false
Timezone=UTC
Packages=
    bash
    dbus-broker
    diffutils
    gawk
    grep
    gzip
    iproute2
    iputils-ping
    kmod
    less
    libseccomp2
    linux-azure
    login
    mount
    nano
    openssh-server
    polkitd
    sed
    strace
    systemd
    systemd-boot
    systemd-boot-efi
    systemd-coredump
    systemd-resolved
    systemd-sysv
    tpm2-tools
    tzdata
    udev
    util-linux

[Output]
Format=disk

[Validation]
Checksum=yes
