[Distribution]
Architecture=x86-64
Distribution=ubuntu
Release=resolute

[Content]
Bootable=false
SourceDateEpoch=0
CleanPackageMetadata=yes
WithDocs=false
Packages=
    cryptsetup-bin
    zstd
    kmod
    mount
    util-linux-extra
    bash

[Output]
Format=cpio
CompressOutput=gzip
Seed=d4f09d27-7e4e-4b1a-9c3a-deadbeef0002
