[Distribution]
Architecture=x86-64
Distribution=ubuntu
Release=resolute

[Content]
Bootable=false
CleanPackageMetadata=yes
WithDocs=false
Packages=
    cryptsetup-bin
    zstd
    kmod
    mount
    util-linux
    bash

[Output]
Format=cpio
CompressOutput=gzip
